services:
    web:
        build:
            context: ./web
        ports:
            - "3001:3001"
        depends_on:
            - api
        env_file:
            - .env
        volumes:
            - ./web/build:/usr/src/app/build
        
    api:
        build:
            context: ./api
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
        env_file:
            - .env
        volumes:
            - media_volume:/usr/share/nginx/html/media
            - ./media/zazil_products:/usr/share/nginx/html/media/zazil_products
            - ./media/zazil_posts:/usr/share/nginx/html/media/zazil_posts
            - ./media/zazil_users:/usr/share/nginx/html/media/zazil_users
            - ./media/zazil_partners:/usr/share/nginx/html/media/zazil_partners

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - static_volume:/usr/share/nginx/html/static
            - media_volume:/usr/share/nginx/html/media
            - ./media/zazil_products:/usr/share/nginx/html/media/zazil_products
            - ./media/zazil_posts:/usr/share/nginx/html/media/zazil_posts
            - ./media/zazil_users:/usr/share/nginx/html/media/zazil_users
            - ./media/zazil_partners:/usr/share/nginx/html/media/zazil_partners
        depends_on:
            - web

    db:
        image: postgres:14
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_HOST=${DB_HOST}
            - POSTGRES_PORT=${DB_PORT}
        env_file:
            - .env
        ports:
            - "5432:5432"

volumes:
    db_data:
    static_volume:
    media_volume:
